#服务端口
server:
  port: 8080

#mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csair?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: root